### PR TITLE
Update frontend challenge requisites

### PR DESCRIPTION
**Pull request by bcentdev**
- I have added clarifications that there are always doubts with the order selector and regarding the behavior of the app when adding a new document.
- I have specified that they must share the repository and be private for security reasons.
- And Typescript is allowed.

### CODE REVIEW

**Comment by ganguera** [comment]
Looks good to me. I'm missing the clarification with the create document section, where we expect to create it in memory.

**Comment by bcentdev** [comment]
> Looks good to me. I'm missing the clarification with the create document section, where we expect to create it in memory.

@ganguera well, I put this clarification in optional features section. I didn't put "in memory" to not determine which is the best solution. The candidate will apply this improvement how he thinks.

[5. New documents created by the user could be displayed at the top of the list.](https://github.com/holdedhub/careers/pull/18/files#diff-40bbc11992a4161ae7bc86bba6aef3ca72cf1fce5252b5572aed112347ce9a39R25)

**Comment by ganguera** [comment]
Nice @bcentdev! Thanks for taking care.

**Review by ganguera — APPROVED** [review]

**Review by dixso — CHANGES_REQUESTED** [review]
I would like to modify some specifications, we will talk privately.

**Review by dixso — APPROVED** [review]

**Pull request merged**
